- name: clone latest ffmpeg
  git: repo=git://source.ffmpeg.org/ffmpeg.git accept_hostkey=true version={{ ffmpeg_version }} dest={{ ffmpeg_source_dir }}/ffmpeg

- name: compile ffmpeg
  environment: ffmpeg_env
  shell: 'cd {{ ffmpeg_source_dir }}/ffmpeg; {{ item }} creates={{ ffmpeg_bin_dir }}/ffmpeg'
  with_items:
    - ./configure --prefix={{ ffmpeg_build }} {{ ffmpeg_flags }}
    - make
    - make install
    - make distclean