- name: apt-get update
  apt: update_cache=yes cache_valid_time=3600

- name: install dependencies
  action: apt pkg={{ item }} state=present
  with_items:
    - git-core
    - autoconf
    - automake
    - build-essential
    - libass-dev
    - libgpac-dev
    - libsdl1.2-dev
    - libtheora-dev
    - libtool
    - libva-dev
    - libvdpau-dev
    - libvorbis-dev
    - pkg-config
    - texi2html
    - zlib1g-dev
    - libmp3lame-dev

- apt: name=libx264-142 state=absent
- apt: name=libx264-dev state=absent

- name: make source folder
  file: dest={{ ffmpeg_source_dir }}/ffmpeg_source state=directory